# Site settings
title: DSpace REST Report Tutorial
description: "description...."
baseurl: "/restReportTutorial" 
url: "http://terrywbrady.github.io/restReportTutorail" 
tagline: Understand your metadata
