title: DSpace 6 REST Report Tutorial
description: "Repoort tools designed for DSpace collection administrators"
baseurl: "/restReportTutorial" 
url: "http://terrywbrady.github.io/restReportTutorial" 
tagline: Understand your metadata
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: UA-297597-14
src_path: "https://github.com/terrywbrady/restReportTutorial/tree/gh-pages"
tpages: "intro,setup/,demo1/,demo2/,demo3/,demo4/,demo5/,demo6/"   
tnames: "Intro,Setup,Demo 1,Demo 2,Demo 3,Demo 4,Demo 5,Demo 6"   
nav:
  - {name: Intro, path: intro}
  - {name: Setup, path: "setup/"}
  - {name: "Demo 1", path: "demo1/"}
