title: DSpace 6 REST Report Tutorial
description: "Repoort tools designed for DSpace collection administrators"
baseurl: "/restReportTutorial" 
url: "http://terrywbrady.github.io/restReportTutorial" 
tagline: Understand your metadata
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: UA-297597-14

# --------------------------------
# Custom additions for the tutorial navigation bar
# --------------------------------

# src_path - used to construct nested links to code files
src_path: "https://github.com/terrywbrady/restReportTutorial/tree/gh-pages"

# nav_style: menu or button
nav_style: menu
nav:
  - {name: Intro,    path: "/intro"}
  - {name: Setup,    path: "/setup/"}
  - {name: "Demo 1", path: "/demo1/"}
  - {name: "Demo 2", path: "/demo2/"}
  - {name: "Demo 3", path: "/demo3/"}
  - {name: "Demo 4", path: "/demo4/"}
  - {name: "Demo 5", path: "/demo5/"}
  - {name: "Demo 6", path: "/demo6/"}
